=== Sophia440/Task04/src/main/resources/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://plants.com"
        xmlns:tns="https://plants.com"
        elementFormDefault="qualified">

    <element name="plants">
        <complexType>
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="tree" type="tns:tree"/>
                <element name="flower" type="tns:flower"/>
            </choice>
        </complexType>
    </element>

    <complexType name="tree">
        <complexContent>
            <extension base="tns:plant">
                <sequence>
                    <element name="leaf-color" type="string"/>
                    <element name="average-height-meters" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="flower">
        <complexContent>
            <extension base="tns:plant">
                <sequence>
                    <element name="petal-color" type="string"/>
                    <element name="average-height-centimeters" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="plant">
        <sequence>
            <element name="name" type="string"/>
            <element name="origin" type="string"/>
            <element name="soil-type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Clay"/>
                        <enumeration value="Sand"/>
                        <enumeration value="Silt"/>
                        <enumeration value="Loams"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="growing-temperature-celsius" type="double"/>
        </sequence>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="ID\d+"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

</schema>

=== Sophia440/Task04/src/main/resources/plants.xml
<?xml version="1.0" encoding="UTF-8"?>
<plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://plants.com/ plants.xsd"
        xmlns="https://plants.com">

    <tree id="ID-1">
        <name>Red Maple</name>
        <origin>Asia</origin>
        <soil-type>Sand</soil-type>
        <growing-temperature-celsius>20.0</growing-temperature-celsius>
        <leaf-color>Red</leaf-color>
        <average-height-meters>30.0</average-height-meters>
    </tree>

    <tree id="ID-2">
        <name>Weeping Willow</name>
        <origin>China</origin>
        <soil-type>Silt</soil-type>
        <growing-temperature-celsius>30.0</growing-temperature-celsius>
        <leaf-color>Green</leaf-color>
        <average-height-meters>10.5</average-height-meters>
    </tree>

    <flower id="ID-3">
        <name>Tulip</name>
        <origin>Central Asia</origin>
        <soil-type>Sand</soil-type>
        <growing-temperature-celsius>9.8</growing-temperature-celsius>
        <petal-color>Assorted</petal-color>
        <average-height-centimeters>35.0</average-height-centimeters>
    </flower>

    <flower id="ID-4">
        <name>Chamomile</name>
        <origin>Germany</origin>
        <soil-type>Clay</soil-type>
        <growing-temperature-celsius>20.0</growing-temperature-celsius>
        <petal-color>White</petal-color>
        <average-height-centimeters>91.0</average-height-centimeters>
    </flower>

</plants>

=== Sophia440/Task04/src/test/resources/test_plants.xml
<?xml version="1.0" encoding="UTF-8"?>
<plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://plants.com/ plants.xsd"
        xmlns="https://plants.com">
    <tree id="ID1">
        <name>Red Maple</name>
        <origin>Asia</origin>
        <soil-type>Sand</soil-type>
        <growing-temperature-celsius>20.0</growing-temperature-celsius>
        <leaf-color>Red</leaf-color>
        <average-height-meters>30.0</average-height-meters>
    </tree>
    <flower id="ID4">
        <name>Chamomile</name>
        <origin>Germany</origin>
        <soil-type>Clay</soil-type>
        <growing-temperature-celsius>20.0</growing-temperature-celsius>
        <petal-color>White</petal-color>
        <average-height-centimeters>91.0</average-height-centimeters>
    </flower>
</plants>
